### ISSUE TITLE
sysread error when using a proxy

### ISSUE THREAD

**Issue by webrunner** [mbbx6spp/twitter4r#5]
if i use a proxy:

Twitter::Client.configure do | conf |
  conf.proxy_host = 'xx.x.x.xxx
  conf.proxy_port = 8081
  conf.proxy_user = 'xxxxxxxx'
  conf.proxy_pass = 'xxxxxxx'
 end 

then i got this error:
ruby-1.8.6-p399/lib/ruby/1.8/net/protocol.rb:133:in `sysread': end of file reached (EOFError)
    from /Users/xxxxxxxx/.rvm/rubies/ruby-1.8.6-p399/lib/ruby/1.8/net/protocol.rb:133:in`rbuf_fill'
    from /Users/xxxxxxx/.rvm/rubies/ruby-1.8.6-p399/lib/ruby/1.8/timeout.rb:62:in `timeout'
    from /Users/xxxxxxx/.rvm/rubies/ruby-1.8.6-p399/lib/ruby/1.8/timeout.rb:93:in`timeout'
    from /Users/xxxxxxx/.rvm/rubies/ruby-1.8.6-p399/lib/ruby/1.8/net/protocol.rb:132:in `rbuf_fill'
    from /Users/xxxxxxx/.rvm/rubies/ruby-1.8.6-p399/lib/ruby/1.8/net/protocol.rb:116:in`readuntil'
    from /Users/xxxxxxx/.rvm/rubies/ruby-1.8.6-p399/lib/ruby/1.8/net/protocol.rb:126:in `readline'
    from /Users/xxxxxxx/.rvm/rubies/ruby-1.8.6-p399/lib/ruby/1.8/net/http.rb:2020:in`read_status_line'
    from /Users/xxxxxxx/.rvm/rubies/ruby-1.8.6-p399/lib/ruby/1.8/net/http.rb:2009:in `read_new'
    from /Users/xxxxxxx/.rvm/rubies/ruby-1.8.6-p399/lib/ruby/1.8/net/http.rb:584:in`connect'
    from /Users/xxxxxxx/.rvm/rubies/ruby-1.8.6-p399/lib/ruby/1.8/net/http.rb:553:in `do_start'
    from /Users/xxxxxxx/.rvm/rubies/ruby-1.8.6-p399/lib/ruby/1.8/net/http.rb:542:in`start'
    from /Users/xxxxxxx/.rvm/gems/ruby-1.8.6-p399/gems/mbbx6spp-twitter4r-0.4.0/lib/twitter/client/base.rb:16:in `http_connect'
    from /Users/xxxxxxx/.rvm/gems/ruby-1.8.6-p399/gems/mbbx6spp-twitter4r-0.4.0/lib/twitter/client/messaging.rb:23:in`messages'
    from ./twitter_pt.rb:18
How can i fix this problem?

**Comment by mbbx6spp** [comment]
Could you provide the actual code as well so I can test it with a local proxy where I am located?  Please be sure to remove any passwords or sensitive information from the code.

**Comment by webrunner** [comment]
Sure:

#!/usr/bin/env ruby

require('rubygems')
gem('mbbx6spp-twitter4r')
require('twitter')  

Twitter::Client.configure do | conf |
  conf.proxy_host = 'xxxxxxxx'
  conf.proxy_port = 8081
  conf.proxy_user = 'xxxxxx'
  conf.proxy_pass = 'xxxxx'
 end

client = Twitter::Client.new(:login => 'flighttest', :password => 'flight098') 

 timeline = client.timeline_for(:me) do |status|
  puts "#{status.user.screen_name}: #{status.text}"
 end

This code works good without the proxy configuration entry. 

Operating System: Mac OSX
Ruby: Tested under 1.8.6 and 1.9.1 with the same result.

Any Advice about the error?

**Comment by webrunner** [comment]
Problem is solved: it was the bad proxy-port. Silly!
But now i have another problem:

When i fire up the script i got this error:

Users/xxxx/.rvm/gems/ruby-1.8.6-p399/gems/mbbx6spp-twitter4r-0.4.0/lib/twitter/client/base.rb:43:in `raise_rest_error': Bad Request (Twitter::RESTError)
    from /Users/xxxx/.rvm/gems/ruby-1.8.6-p399/gems/mbbx6spp-twitter4r-0.4.0/lib/twitter/client/base.rb:48:in`handle_rest_response'
    from /Users/xxxx/.rvm/gems/ruby-1.8.6-p399/gems/mbbx6spp-twitter4r-0.4.0/lib/twitter/client/base.rb:20:in `http_connect'
    from /Users/xxxx/.rvm/rubies/ruby-1.8.6-p399/lib/ruby/1.8/net/http.rb:543:in`start'
    from /Users/xxxx/.rvm/gems/ruby-1.8.6-p399/gems/mbbx6spp-twitter4r-0.4.0/lib/twitter/client/base.rb:16:in `http_connect'
    from /Users/xxxx/.rvm/gems/ruby-1.8.6-p399/gems/mbbx6spp-twitter4r-0.4.0/lib/twitter/client/user.rb:61:in`my'
    from ./twitter_pt.rb:40

What´s wrong? Can you help me?
